# Default markdownlint configuration
default: true

# Line length - be more lenient for documentation
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  tables: false

# Allow multiple top-level headings for API docs
MD025: false

# Allow inline HTML for better formatting
MD033: false

# Allow bare URLs for convenience
MD034: false

# Disable requirement for blank line after heading (allows more compact docs)
MD022: false

# Allow emphasis markers without surrounding spaces  
MD036: false

# Allow trailing punctuation in headings
MD026: false

# Allow duplicate headings (common in API docs)
MD024:
  siblings_only: true

# Allow HTML in markdown for enhanced formatting
MD033:
  allowed_elements: ['br', 'sub', 'sup', 'kbd', 'details', 'summary']

# Be more lenient with list indentation
MD007:
  indent: 2

# Allow fenced code blocks without language specification
MD040: false

# Allow first line in file to not be top level heading
MD041: false